### ISSUE TITLE
Port fixes from jasmine-flight

### ISSUE THREAD

**Issue by necolas** [flightjs/mocha-flight#3]
- [ ] Fix null values causing validateHash to fail.
- [x] Fix setupComponent unnecessarily wrapping fixtures in a div.

**Comment by jared-stilwell** [comment]
@necolas if the "Fix null values causing validateHash to fail." issue still exists, could you provide some detail on how to reproduce it?

**Comment by jared-stilwell** [comment]
Closing this since I'm not sure what the first item in the description refers to.
